// <auto-generated />
using System;
using ApiPeaje.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPeaje.Migrations
{
    [DbContext(typeof(ApplicationdDbContext))]
    [Migration("20240617205414_MigrationPEDIVEXEXPORTACIONpeajes")]
    partial class MigrationPEDIVEXEXPORTACIONpeajes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiPeaje.Models.Peaje", b =>
                {
                    b.Property<int>("PeajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdCategoriaTarifa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombrePeaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("PeajeId");

                    b.ToTable("peajes");
                });
#pragma warning restore 612, 618
        }
    }
}
